package UI;

import chat.ChatClient;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.Mixer;
import javax.sound.sampled.SourceDataLine;
import javax.sound.sampled.TargetDataLine;
import voice.Player;
import voice.Recorder;

public class invite_ui extends javax.swing.JFrame {
    public InetAddress fr_ip;
    public int my_port;
    public String my_ip;
    
    DatagramSocket datagramSocket;
    Recorder r;
    Player p;
    static Mixer.Info[] mixerInfo = AudioSystem.getMixerInfo();
        
    SourceDataLine audio_out;
    TargetDataLine audio_in;
    
    public invite_ui() {
        initComponents();  
    }
    
    public void init_audio(){
        try {
            AudioFormat format = getAudioFormat();
            DataLine.Info info_in = new DataLine.Info(TargetDataLine.class, format);
            DataLine.Info info_out = new DataLine.Info(SourceDataLine.class, format);
            if (!AudioSystem.isLineSupported(info_in)) {
                System.out.println("Âm thanh đầu vào không hỗ trợ");
                System.exit(0);
            }
            if(!AudioSystem.isLineSupported(info_out)){
                System.out.println("Âm thanh đầu vào không hỗ trợ");
                System.exit(0);
            }
            audio_out = (SourceDataLine)AudioSystem.getLine(info_out);
            audio_out.open(format);
            audio_out.start();
            
            audio_in = (TargetDataLine) AudioSystem.getLine(info_in);
            audio_in.open(format);
            audio_in.start();            
        } catch (LineUnavailableException ex) {
            Logger.getLogger(invite_ui.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }
    
    public void init_player(){
        try {
            p = new Player();
            datagramSocket = new DatagramSocket(0);
            p.din = datagramSocket;
            p.audio_out = audio_out;
            my_ip = InetAddress.getLocalHost().getHostAddress();
            my_port = datagramSocket.getLocalPort();
            System.out.println("My ip: "+my_ip+" cổng: "+datagramSocket.getLocalPort());
            p.start();
        } catch (SocketException | UnknownHostException ex) {
            Logger.getLogger(invite_ui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void init_recorder(InetAddress ia,int port){
        System.out.println("call in init recorder:"+ ia.toString()+port);
        r = new Recorder();
        r.dout = datagramSocket;
        r.audio_in = audio_in;
        r.fr_ip = ia;
        r.fr_port = port;
        r.start();
    }
    
    public static AudioFormat getAudioFormat(){
        float sampleRate = 8000.0F;
        int sampleSizeInBits = 16;
        int channels = 2;
        boolean signed = true;
        boolean bigEndian = false;
        return new AudioFormat(sampleRate, sampleSizeInBits, channels, signed,bigEndian);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_status = new javax.swing.JLabel();
        btn_end_call = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        lb_status.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_status.setText("Đang mời");

        btn_end_call.setBackground(new java.awt.Color(255, 48, 48));
        btn_end_call.setText("Hủy");
        btn_end_call.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_end_callActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_end_call, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lb_status, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_end_call)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_end_callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_end_callActionPerformed
        ChatClient.playing = false;
        this.dispose();
    }//GEN-LAST:event_btn_end_callActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invite_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new invite_ui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_end_call;
    public javax.swing.JLabel lb_status;
    // End of variables declaration//GEN-END:variables
}
