/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.DataSocket;
import chat.ChatClient;
import chat.MyServer;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author thanh
 */
public class one_two_three extends javax.swing.JFrame {
    public int fingerValue = 5;
    private MyServer myServer;

    /**
     * Creates new form one_two_three
     */
    public one_two_three() {
        initComponents();
        myServer = new MyServer(ChatClient.myServerPort);
    }

    public void startCount() {
        //start thread server con
        myServer.start();

        Thread countDown = new Thread(() -> {
            for (int i = 10; i >= 0; i--) {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(one_two_three.class.getName()).log(Level.SEVERE, null, ex);
                }
                txt_count.setText(Integer.toString(i));
            }
            txt_count.setText("Hết giờ");
            showMyFinger();
        });
        countDown.start();
    }

    private void showMyFinger() {
        String finger = MyServer.fingerValue;
        
        if (finger != null) {
            if (finger.contains("bua")) {
                txt_myFinger.setText("Bạn ra búa");
                fingerValue = 1;
            } else if (finger.contains("keo")) {
                txt_myFinger.setText("Bạn ra kéo");
                fingerValue = 2;
            } else if (finger.contains("bao")) {
                txt_myFinger.setText("Bạn ra bao");
                fingerValue = 3;
            } else if (finger.contains("ukn")) {
                txt_myFinger.setText("Bạn không ra gì");
                fingerValue = 4;
            } else {
                txt_myFinger.setText("Unknown");
                txt_myFinger.setText("Bạn không ra gì");
                fingerValue = 5;
            }
        } else {
            txt_myFinger.setText("Bạn không ra gì");
        }
        
        try {
            sendData(fingerValue);
        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(one_two_three.class.getName()).log(Level.SEVERE, null, ex);
        }
        myServer.stop();
    }

    private void sendData(int fingerValue) throws IOException, InterruptedException {
        OutputStream outputStream = ChatClient.socket.getOutputStream();
        ObjectOutputStream objectOutputStream = new ObjectOutputStream(outputStream);

        DataSocket dtsk = new DataSocket();
        String[] data = new String[3];
        dtsk.action = "sendfinger";
        data[0] = ChatClient.myUserName;
        data[1] = ChatClient.myRivalUserName;
        data[2] = String.valueOf(fingerValue);
        dtsk.data = data;

        objectOutputStream.writeObject(dtsk);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_fingerValue = new javax.swing.JTextArea();
        txt_count = new javax.swing.JLabel();
        txt_myFinger = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Oẳn tù tì");

        txt_fingerValue.setColumns(20);
        txt_fingerValue.setRows(5);
        jScrollPane1.setViewportView(txt_fingerValue);

        txt_count.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        txt_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txt_myFinger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_myFinger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
            .addComponent(txt_count, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(txt_myFinger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_count, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_myFinger, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(one_two_three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(one_two_three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(one_two_three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(one_two_three.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new one_two_three().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel txt_count;
    public javax.swing.JTextArea txt_fingerValue;
    private javax.swing.JLabel txt_myFinger;
    // End of variables declaration//GEN-END:variables
}
